project_id = "ympsdduubddnzrktqdgu"
purl = "https://tpccvnkshnphsofmvawd.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwY2N2bmtzaG5waHNvZm12YXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTIxMzcsImV4cCI6MjA2ODU4ODEzN30.fVjUiirtXIwZd3Zliqr-3F50zq7yXWFjV4jP4nx2X2M"