[build]
  base = "/"
  publish = "dist"
  command = "yarn install && yarn build"

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
