// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ympsdduubddnzrktqdgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltcHNkZHV1YmRkbnpya3RxZGd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzkyODUsImV4cCI6MjA2NTc1NTI4NX0.lOkNNRncZadYBEDDnR0J2t9Q4XSBJABmL-kcxNwwulM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);